env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  'quotes': ['error', 'single'],
  'indent': ['error', 2],
  'no-multi-spaces': ['error'],
  'semi': ['error', 'never'],
  'no-unused-vars': 'off',
  'react/prop-types': 'off',
  'indent': ['error', 2],
  "prettier/prettier": [
    2,
    {
        "trailingComma": "es5",
        "singleQuote": true,
        "printWidth": 100,
        "endOfLine": "lf"
    }
  ],
  "max-len": [2, 100],
}
